[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remmapings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/"]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./img" },
]

baseSepolia = "https://sepolia.base.org"

[etherscan]
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }